name: Deploy WordPress via FTP

on:
  push:
    branches:
      - main  # Deploy from main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate wp-config.php
        run: |
          cat > wp-config.php <<EOL
          <?php
          define( 'DB_NAME', '${{ secrets.DB_NAME }}' );
          define( 'DB_USER', '${{ secrets.DB_USER }}' );
          define( 'DB_PASSWORD', '${{ secrets.DB_PASSWORD }}' );
          define( 'DB_HOST', '${{ secrets.DB_HOST }}' );
          define( 'DB_CHARSET', 'utf8mb3' );
          define( 'DB_COLLATE', '' );
          
          define( 'AUTH_KEY',         '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 1p)' );
          define( 'SECURE_AUTH_KEY',  '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 2p)' );
          define( 'LOGGED_IN_KEY',    '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 3p)' );
          define( 'NONCE_KEY',        '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 4p)' );
          define( 'AUTH_SALT',        '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 5p)' );
          define( 'SECURE_AUTH_SALT', '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 6p)' );
          define( 'LOGGED_IN_SALT',   '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 7p)' );
          define( 'NONCE_SALT',       '$(curl -s https://api.wordpress.org/secret-key/1.1/salt/ | sed -n 8p)' );

          define( 'WP_ENVIRONMENT_TYPE', '${{ secrets.WP_ENVIRONMENT_TYPE }}' );

          \$table_prefix = 'q7xs_';

          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          define( 'WP_DEBUG_DISPLAY', true );
          @ini_set('display_errors', 0);

          if ( ! defined( 'ABSPATH' ) ) {
            define( 'ABSPATH', dirname(__FILE__) . '/' );
          }
          require_once ABSPATH . 'wp-settings.php';
          EOL

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
